### ISSUE TITLE
[Crop Cycle] Flexible date management for tasks

### ISSUE THREAD

**Issue by Alchez** [ERPNext-Agri-Community/erpnext-agri#1]
## Problem statement

When managing tasks for a Crop Cycle, some days may be absolute from the start date while others may be dependent on other parameters.

## Challenges
Use Cases:
- Fixed interval: X days from start
- Time-dependent interval: X days from preceding task
- Weather-dependent interval: X degree days/ total insolation
- Condition-dependent interval: when crop is X condition, based on sample
- Date-based: task on x date, regardless of other conditions (harvest the flowers before the holiday!)

Considerations:
- On contracting a disease, the succeeding Crop Cycle tasks should automatically shift, only if needed, to accommodate for tasks required for managing the disease.

## Possible solution(s)
- Leverage Frappe's ability to create nested tasks in order to manage and group similar tasks.

## Checklist:
- [ ] Finalized on solution (out of several)
- [ ] Finalized on solution implementation (of one)
- [ ] Implemented solution (as code)
- [ ] Made PR (link to PR here please)

**Comment by agritheory** [comment]
Time use cases to consider in design:
Fixed interval: X days from start
Time-dependent interval: X days from preceding task
Weather-dependent interval: X degree days/ total insolation
Condition-dependent interval: when crop is X condition, based on sample
Date-based: task on x date, regardless of other conditions (harvest the flowers before the holiday!) 

Adding complexity, don't see how it can be avoided... grrrrr
