### ISSUE TITLE
[Crop Cycle] Discuss the use of the "Cycle Type" field

### ISSUE THREAD

**Issue by Alchez** [ERPNext-Agri-Community/erpnext-agri#2]
## Problem statement
There's no clear consensus on the use of the "Cycle Type" field for individual crop plantings. We'll need to discuss this more.

## Possible solution to Problem
- Have it mirror the "Type" field in the Crop doctype and keep it read-only.
- Maybe remove it entirely and only have that data in the Crop doctype.

## Checklist :
- [ ] Finalized on solution (out of several)
- [ ] Finalized on solution implementation (of one)
- [ ] Implemented solution (as code)
- [ ] Made PR (link to PR here please)

**Comment by Tropicalrambler** [comment]
Cycle type, form what I recall, referred to Annual, Biennial, etc.  It helps establish out of the gate whether this crop will be treated as a "harvest once only and dump"  or a "harvest several times, and then dump".
In agriculture we deal with these **events**:
**Planting or Px**:  Date of planting the seeds.
**Transplant or Tx**: Date of transplanting the growing plants at any stage. A plant can have "N" number of transplants.
**Harvest or Cx (Cut)**: Date of cutting. A plant can have several Cuts per crop cycle.
**Dump or Dx**: Date of Dumping. This is the day that you will eliminate the crop completely. It is a special type of harvest in that output could theoretically be generated, but it is the last one for that Crop Cycle.
